### ISSUE TITLE
Include TTGO T9 board in config

### ISSUE THREAD

**Issue by Aggebitter** [marcel-licence/ml_synth_multi_saw_example#3]
Defined board in ml_boards.h is missing in config.
Add this line ?

`//#define BOARD_TTGO_T9_RGB_LED_WM8978 /* activate this when using the TTGO T9 Audio Kit with the WM8978 codec */`

// Agge

**Comment by Aggebitter** [comment]
Made a commit Closing

**Comment by marcel-licence** [comment]
Thank you!
